name: telegram-bot-silencer
channels:
  - defaults
dependencies:
  - python=3.8
  - black
  - pip
  - pip:
    - argparse
    - python-telegram-bot==13.15
    - transformers==4.29.2
    - librosa==0.10.1
    - urllib3==1.26.16
